name: BlackLists updater

#env:
#  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Blacklists/update'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this is required to fetch all history for all branches and tags
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: ./blacklists_updater.sh
      - run: cat blacklist*txt
      - run: git diff
      - run: git status
