name: BlackLists updater

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PUSH }}
  REPO_NAME: AS_Network_List
  REPO_OWNER: C24Be

on:
  workflow_dispatch:
  schedule:
    # At 00:00 on the first day of the month
    #- cron: '0 0 1 * *'
    # At 00:00 on Sunday
    #- cron: '0 0 * * 0'
    # At 00:00 every day
    - cron: '0 0 * * *'
    # Every hour
    #- cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    name: 'BL/Update'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this is required to fetch all history for all branches and tags
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: ./requirements.sh
      - run: ./blacklists_updater.sh
      - run: curl ifconfig.io -q
      - run: |
          timestamp=`date "+%Y-%m-%d_%H-%M-%S"`
          git config --global user.name "${{ env.REPO_OWNER }}"
          git config --global user.email "${{ env.REPO_OWNER }}@github.com"
          git status
          git diff
          git add blacklist*txt
          git commit -m "Update blacklists: $timestamp"
          git push https://${{ env.REPO_OWNER }}:${{ env.GITHUB_TOKEN }}@github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git
