name: BlackLists updater

#env:
#  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

on:
  workflow_dispatch:
  schedule:
    # At 00:00 on the first day of the month
    #- cron: '0 0 1 * *'
    # At 00:00 on Sunday
    #- cron: '0 0 * * 0'
    # At 00:00 every day
    - cron: '0 0 * * *'
    # Every hour
    #- cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    name: 'BL/Update'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this is required to fetch all history for all branches and tags
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: ./blacklists_updater.sh
      - run: curl ifconfig.io
      - run: |
          timestamp=`date "+%Y-%m-%d_%H-%M-%S"`
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git status
          git diff
          git add blacklist*txt
          git commit -m "Update blacklists: $timestamp"
          git push
        env:
          GH_PAT: ${{ secrets.GH_TOKEN_PUSH }}
