name: BlackLists updater

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  REPO_NAME: AS_Network_List
  REPO_OWNER: C24Be

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    name: 'Update'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/pyInstall
      - run: ./blacklists_updater.sh
      - uses: ./.github/actions/gitPush
        env:
          PUSH_FILES: auto/*txt
